type DamageType = "physical-damage" | "magic-damage" | "true-damage";

type ChampionTags = {
  damageTypes?: DamageType[];
  tags?: string[];
  counters?: string[];
  strongAgainst?: string[];
  weakAgainst?: string[];
  synergiesWith?: string[];
};

export const championTags: Record<string, ChampionTags> = {
  Aatrox: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Ahri: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "assassin", "strong-ultimate"],
  },
  Akali: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Akshan: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Alistar: {
    tags: ["dash", "cc", "strong-ultimate"],
    synergiesWith: ["Kalista"],
  },
  Ambessa: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Amumu: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "strong-ultimate"],
    synergiesWith: ["MissFortune"],
  },
  Anivia: { damageTypes: ["magic-damage"] },
  Annie: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Aphelios: { damageTypes: ["physical-damage"] },
  Ashe: { damageTypes: ["physical-damage"], tags: ["strong-ultimate"] },
  AurelionSol: { damageTypes: ["magic-damage"] },
  Aurora: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Azir: { damageTypes: ["magic-damage"], tags: ["dash", "strong-ultimate"] },
  Bard: { tags: ["cc"] },
  Belveth: { damageTypes: ["physical-damage"] },
  Blitzcrank: { tags: ["cc"] },
  Brand: { damageTypes: ["magic-damage"] },
  Braum: { synergiesWith: ["Lucian"] },
  Briar: { damageTypes: ["physical-damage"] },
  Caitlyn: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Camille: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["dash"],
    synergiesWith: ["Galio"],
  },
  Cassiopeia: { damageTypes: ["magic-damage"], strongAgainst: ["dash"] },
  Chogath: { damageTypes: ["magic-damage"] },
  Corki: {
    damageTypes: ["magic-damage", "physical-damage"],
    tags: ["dash"],
  },
  Darius: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["healing"],
  },
  Diana: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Draven: { damageTypes: ["physical-damage"] },
  DrMundo: {
    damageTypes: ["magic-damage"],
    tags: ["healing", "strong-ultimate"],
  },
  Ekko: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "healing", "assassin"],
  },
  Elise: { damageTypes: ["magic-damage"] },
  Evelynn: { damageTypes: ["magic-damage"], tags: ["assassin"] },
  Ezreal: { damageTypes: ["magic-damage", "physical-damage"] },
  Fiddlesticks: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Fiora: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["dash", "healing"],
  },
  Fizz: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Galio: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "cc", "strong-ultimate"],
    synergiesWith: ["Camille", "JarvanIV"],
  },
  Gangplank: {
    damageTypes: ["physical-damage", "true-damage"],
    strongAgainst: ["cc"],
  },
  Garen: { damageTypes: ["physical-damage", "true-damage"] },
  Gnar: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Gragas: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Graves: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Gwen: { damageTypes: ["magic-damage", "true-damage"], tags: ["dash"] },
  Hecarim: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Heimerdinger: { damageTypes: ["magic-damage"] },
  Hwei: { damageTypes: ["magic-damage"] },
  Illaoi: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Irelia: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Ivern: { damageTypes: ["magic-damage"] },
  Janna: {
    damageTypes: ["magic-damage"],
    tags: ["healing"],
    strongAgainst: ["assassin"],
  },
  JarvanIV: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    synergiesWith: ["Galio"],
  },
  Jax: { damageTypes: ["physical-damage", "magic-damage"], tags: ["dash"] },
  Jayce: { damageTypes: ["physical-damage"] },
  Jhin: { damageTypes: ["physical-damage"] },
  Jinx: { damageTypes: ["physical-damage"] },
  Kaisa: { damageTypes: ["magic-damage", "physical-damage"] },
  Kalista: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    synergiesWith: ["Alistar", "Neeko"],
  },
  Karma: { damageTypes: ["magic-damage"] },
  Karthus: { damageTypes: ["magic-damage"] },
  Kassadin: { damageTypes: ["magic-damage"], tags: ["assassin"] },
  Katarina: {
    damageTypes: ["magic-damage"],
    tags: ["assassin"],
    strongAgainst: ["healing"],
    weakAgainst: ["cc"],
  },
  Kayle: {
    damageTypes: ["magic-damage", "physical-damage"],
    tags: ["strong-ultimate"],
    strongAgainst: ["assassin"],
  },
  Kayn: {
    damageTypes: ["physical-damage"],
    tags: ["dash", "healing", "assassin"],
  },
  Kennen: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Khazix: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Kindred: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Kled: { damageTypes: ["physical-damage"], strongAgainst: ["healing"] },
  KogMaw: { damageTypes: ["magic-damage", "physical-damage"] },
  KSante: { damageTypes: ["physical-damage"] },
  Leblanc: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  LeeSin: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Leona: { tags: ["dash", "cc"] },
  Lillia: { damageTypes: ["magic-damage", "true-damage"] },
  Lissandra: {
    damageTypes: ["magic-damage"],
    tags: ["cc", "strong-ultimate"],
    strongAgainst: ["assassin"],
  },
  Lucian: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    synergiesWith: ["Braum"],
  },
  Lulu: { damageTypes: ["magic-damage"], strongAgainst: ["assassin"] },
  Lux: { damageTypes: ["magic-damage"] },
  Malphite: {
    damageTypes: ["magic-damage"],
    tags: ["strong-ultimate"],
    synergiesWith: ["Yasuo", "Yone", "MissFortune", "Orianna"],
  },
  Malzahar: {
    damageTypes: ["magic-damage"],
    tags: ["cc"],
    strongAgainst: ["assassin"],
  },
  Maokai: {
    damageTypes: ["magic-damage"],
    tags: ["healing", "strong-ultimate", "cc"],
  },
  MasterYi: {
    damageTypes: ["physical-damage", "true-damage"],
    synergiesWith: ["Zilean"],
    weakAgainst: ["cc"],
  },
  Milio: {
    damageTypes: ["magic-damage"],
    tags: ["healing"],
    strongAgainst: ["cc"],
  },
  MissFortune: {
    damageTypes: ["physical-damage"],
    synergiesWith: ["Amumu", "Malphite"],
  },
  MonkeyKing: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Mordekaiser: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Morgana: {
    damageTypes: ["magic-damage"],
    tags: ["cc"],
    strongAgainst: ["cc"],
  },
  Naafiri: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Nami: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Nasus: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Nautilus: { tags: ["cc"] },
  Neeko: { damageTypes: ["magic-damage"], synergiesWith: ["Kalista"] },
  Nidalee: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Nilah: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Nocturne: { damageTypes: ["physical-damage"], synergiesWith: ["Orianna"] },
  Nunu: { damageTypes: ["magic-damage"] },
  Olaf: {
    damageTypes: ["physical-damage", "true-damage"],
    strongAgainst: ["cc"],
  },
  Orianna: {
    damageTypes: ["magic-damage"],
    tags: ["strong-ultimate"],
    synergiesWith: ["Nocturne", "Malphite", "Yasuo", "Rakan"],
  },
  Ornn: { damageTypes: ["magic-damage"] },
  Pantheon: { damageTypes: ["physical-damage"] },
  Poppy: { damageTypes: ["physical-damage"], strongAgainst: ["dash"] },
  Pyke: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Qiyana: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Quinn: { damageTypes: ["physical-damage"] },
  Rakan: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "healing"],
    synergiesWith: ["Xayah", "Orianna"],
  },
  Rammus: { damageTypes: ["magic-damage"] },
  RekSai: { damageTypes: ["physical-damage"] },
  Rell: {},
  Renata: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Renekton: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Rengar: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Riven: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Rumble: { damageTypes: ["magic-damage"] },
  Ryze: { damageTypes: ["magic-damage"] },
  Samira: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Sejuani: { damageTypes: ["magic-damage"], tags: ["dash", "strong-ultimate"] },
  Senna: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Seraphine: {
    damageTypes: ["magic-damage"],
    tags: ["healing", "strong-ultimate"],
  },
  Sett: { damageTypes: ["physical-damage", "true-damage"] },
  Shaco: {
    damageTypes: ["physical-damage", "magic-damage"],
    tags: ["assassin"],
  },
  Shen: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "strong-ultimate", "cc"],
  },
  Shyvana: { damageTypes: ["magic-damage", "physical-damage"] },
  Singed: { damageTypes: ["magic-damage"], strongAgainst: ["healing"] },
  Sion: { damageTypes: ["physical-damage"], tags: ["cc"] },
  Sivir: { damageTypes: ["physical-damage"] },
  Skarner: { damageTypes: ["physical-damage"] },
  Smolder: { damageTypes: ["magic-damage", "physical-damage"] },
  Sona: { damageTypes: ["magic-damage"], tags: ["healing", "strong-ultimate"] },
  Soraka: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Swain: {
    damageTypes: ["magic-damage"],
    tags: ["healing", "strong-ultimate"],
  },
  Sylas: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "healing"],
    strongAgainst: ["strong-ultimate"],
  },
  Syndra: { damageTypes: ["magic-damage"], tags: ["cc"] },
  TahmKench: { damageTypes: ["magic-damage"], strongAgainst: ["assassin"] },
  Taliyah: { damageTypes: ["magic-damage"], strongAgainst: ["dash"] },
  Talon: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Taric: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Teemo: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Thresh: { tags: ["cc"] },
  Tristana: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Trundle: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Tryndamere: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  TwistedFate: { damageTypes: ["magic-damage"], counters: ["Shaco"] },
  Twitch: { damageTypes: ["physical-damage"] },
  Udyr: { damageTypes: ["physical-damage"] },
  Urgot: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Varus: {
    damageTypes: ["physical-damage", "magic-damage"],
    tags: ["strong-ultimate", "cc"],
    strongAgainst: ["healing"],
  },
  Vayne: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["dash"],
  },
  Veigar: { damageTypes: ["magic-damage"], tags: ["cc"] },
  Velkoz: { damageTypes: ["magic-damage", "true-damage"] },
  Vex: { damageTypes: ["magic-damage"] },
  Vi: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Viego: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Viktor: { damageTypes: ["magic-damage"] },
  Vladimir: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Volibear: {
    damageTypes: ["magic-damage", "physical-damage"],
    tags: ["healing"],
  },
  Warwick: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Xayah: { damageTypes: ["physical-damage"], synergiesWith: ["Rakan"] },
  Xerath: { damageTypes: ["magic-damage"] },
  XinZhao: { damageTypes: ["physical-damage"], tags: ["dash", "cc"] },
  Yasuo: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    synergiesWith: ["Malphite", "Orianna", "Gragas"],
  },
  Yone: {
    damageTypes: ["physical-damage", "magic-damage"],
    tags: ["dash", "strong-ultimate"],
  },
  Yorick: { damageTypes: ["physical-damage"] },
  Yuumi: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Zac: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Zed: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Zeri: { damageTypes: ["physical-damage"] },
  Ziggs: { damageTypes: ["magic-damage"] },
  Zilean: {
    damageTypes: ["magic-damage"],
    tags: ["strong-ultimate"],
    strongAgainst: ["assassin"],
    counters: ["Galio"],
    synergiesWith: ["MasterYi"],
  },
  Zoe: { damageTypes: ["magic-damage"] },
  Zyra: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Mel: { damageTypes: ["magic-damage"] },
};
