export const championTags = {
  Aatrox: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Ahri: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "assassin", "strong-ultimate"],
  },
  Akali: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Akshan: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Alistar: {
    tags: ["dash", "cc", "strong-ultimate"],
    synergiesWith: ["Kalista"],
  },
  Ambessa: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Ammu: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "strong-ultimate"],
    synergiesWith: ["MissFortune"],
  },
  Anivia: { damageTypes: ["magic-damage"] },
  Annie: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Aphelios: { damageTypes: ["physical-damage"] },
  Ashe: { damageTypes: ["physical-damage"], tags: ["strong-ultimate"] },
  AurelionSol: { damageTypes: ["magic-damage"] },
  Aurora: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Azir: { damageTypes: ["magic-damage"], tags: ["dash", "strong-ultimate"] },
  Bard: { tags: ["cc"] },
  Belveth: { damageTypes: ["physical-damage"] },
  Blitzcrank: { tags: ["cc"] },
  Brand: { damageTypes: ["magic-damage"] },
  Braum: { synergiesWith: ["Lucian"] },
  Briar: { damageTypes: ["physical-damage"] },
  Caitlyn: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Camille: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["dash"],
    synergiesWith: ["Galio"],
  },
  Cassiopeia: { damageTypes: ["magic-damage"], strongAgainst: ["dash"] },
  Chogath: { damageTypes: ["magic-damage"] },
  Corki: { damageTypes: ["magic-damage", "physical-damage"], tags: ["dash"] },
  Darius: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["healing"],
  },
  Diana: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Draven: { damageTypes: ["physical-damage"] },
  DrMundo: {
    damageTypes: ["magic-damage"],
    tags: ["healing", "strong-ultimate"],
  },
  Ekko: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "healing", "assassin"],
  },
  Elise: { damageTypes: ["magic-damage"] },
  Evelynn: { damageTypes: ["magic-damage"], tags: ["assassin"] },
  Ezreal: { damageTypes: ["magic-damage", "physical-damage"] },
  Fiddlesticks: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Fiora: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["dash", "healing"],
  },
  Fizz: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Galio: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "cc", "strong-ultimate"],
    synergiesWith: ["Camille", "JarvanIV"],
  },
  Gangplank: {
    damageTypes: ["physical-damage", "true-damage"],
    strongAgainst: ["cc"],
  },
  Garen: { damageTypes: ["physical-damage", "true-damage"] },
  Gnar: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Gragas: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Graves: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Gwen: { damageTypes: ["magic-damage", "true-damage"], tags: ["dash"] },
  Hecarim: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Heimerdinger: { damageTypes: ["magic-damage"] },
  Hwei: { damageTypes: ["magic-damage"] },
  Illaoi: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Irelia: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Ivern: { damageTypes: ["magic-damage"] },
  Janna: {
    damageTypes: ["magic-damage"],
    tags: ["healing"],
    strongAgainst: ["assassin"],
  },
  JarvanIV: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    synergiesWith: ["Galio"],
  },
  Jax: { damageTypes: ["physical-damage", "magic-damage"], tags: ["dash"] },
  Jayce: { damageTypes: ["physical-damage"] },
  Jhin: { damageTypes: ["physical-damage"] },
  Jinx: { damageTypes: ["physical-damage"] },
  Kaisa: { damageTypes: ["physical-damage", "magic-damage"], tags: ["dash"] },
  Kalista: { damageTypes: ["physical-damage"], synergiesWith: ["Alistar"] },
  Karma: { damageTypes: ["magic-damage"] },
  Karthus: { damageTypes: ["magic-damage"], tags: ["strong-ultimate"] },
  Kassadin: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Katarina: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  Kayle: {
    damageTypes: ["magic-damage", "physical-damage"],
    tags: ["healing"],
  },
  Kayn: {
    damageTypes: ["physical-damage"],
    tags: ["dash", "healing", "assassin"],
  },
  Kennen: { damageTypes: ["magic-damage"], tags: ["dash"] },
  Khazix: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Kindred: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Kled: { damageTypes: ["physical-damage"], tags: ["dash"] },
  KogMaw: { damageTypes: ["magic-damage", "physical-damage"] },
  Leblanc: { damageTypes: ["magic-damage"], tags: ["dash", "assassin"] },
  LeeSin: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Leona: { damageTypes: ["magic-damage"], tags: ["dash", "cc"] },
  Lillia: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Lissandra: { damageTypes: ["magic-damage"], tags: ["dash", "cc"] },
  Lucian: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    synergiesWith: ["Braum"],
  },
  Lulu: { damageTypes: ["magic-damage"] },
  Lux: { damageTypes: ["magic-damage"] },
  Malphite: {
    damageTypes: ["magic-damage"],
    tags: ["dash"],
    strongAgainst: ["physical-damage"],
  },
  Malzahar: { damageTypes: ["magic-damage"] },
  Maokai: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  MasterYi: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["dash", "healing"],
  },
  Milio: { damageTypes: ["magic-damage"], tags: ["healing"] },
  MissFortune: { damageTypes: ["physical-damage"], synergiesWith: ["Ammu"] },
  Mordekaiser: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Morgana: { damageTypes: ["magic-damage"] },
  Nami: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Nasus: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Nautilus: { damageTypes: ["magic-damage"], tags: ["dash", "cc"] },
  Neeko: { damageTypes: ["magic-damage"] },
  Nidalee: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Nilah: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Nocturne: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Nunu: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Olaf: {
    damageTypes: ["physical-damage", "true-damage"],
    tags: ["healing"],
    strongAgainst: ["cc"],
  },
  Orianna: { damageTypes: ["magic-damage"] },
  Ornn: { damageTypes: ["magic-damage"], tags: ["dash"] },
  Pantheon: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Poppy: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    strongAgainst: ["dash"],
  },
  Pyke: {
    damageTypes: ["physical-damage"],
    tags: ["dash", "healing", "assassin"],
  },
  Qiyana: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Quinn: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Rakan: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Rammus: {
    damageTypes: ["magic-damage"],
    tags: ["dash"],
    strongAgainst: ["physical-damage"],
  },
  RekSai: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Rell: { damageTypes: ["magic-damage"], tags: ["dash", "cc"] },
  Renata: { damageTypes: ["magic-damage"] },
  Renekton: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Rengar: {
    damageTypes: ["physical-damage"],
    tags: ["dash", "healing", "assassin"],
  },
  Riven: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Rumble: { damageTypes: ["magic-damage"] },
  Ryze: { damageTypes: ["magic-damage"] },
  Samira: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Sejuani: { damageTypes: ["magic-damage"], tags: ["dash", "cc"] },
  Senna: { damageTypes: ["physical-damage"] },
  Seraphine: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Sett: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Shaco: { damageTypes: ["physical-damage"], tags: ["assassin"] },
  Shen: { damageTypes: ["magic-damage"] },
  Shyvana: { damageTypes: ["magic-damage", "physical-damage"] },
  Singed: { damageTypes: ["magic-damage"] },
  Sion: { damageTypes: ["physical-damage"] },
  Sivir: { damageTypes: ["physical-damage"] },
  Skarner: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Sona: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Soraka: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Swain: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Sylas: {
    damageTypes: ["magic-damage"],
    tags: ["dash", "healing"],
    strongAgainst: ["strong-ultimate"],
  },
  Syndra: { damageTypes: ["magic-damage"] },
  TahmKench: { damageTypes: ["magic-damage"] },
  Taliyah: { damageTypes: ["magic-damage"] },
  Talon: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Taric: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Teemo: { damageTypes: ["magic-damage"] },
  Thresh: { damageTypes: ["magic-damage"], tags: ["dash"] },
  Tristana: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Trundle: { damageTypes: ["physical-damage"], tags: ["healing"] },
  Tryndamere: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  TwistedFate: { damageTypes: ["magic-damage"] },
  Twitch: { damageTypes: ["physical-damage"] },
  Udyr: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Urgot: { damageTypes: ["physical-damage"] },
  Varus: { damageTypes: ["physical-damage", "magic-damage"] },
  Vayne: { damageTypes: ["physical-damage", "true-damage"], tags: ["dash"] },
  Veigar: { damageTypes: ["magic-damage"] },
  Velkoz: { damageTypes: ["magic-damage", "true-damage"] },
  Vex: { damageTypes: ["magic-damage"] },
  Vi: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Viego: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Viktor: { damageTypes: ["magic-damage"] },
  Vladimir: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Volibear: {
    damageTypes: ["physical-damage", "magic-damage"],
    tags: ["dash", "healing"],
  },
  Warwick: {
    damageTypes: ["physical-damage", "magic-damage"],
    tags: ["dash", "healing"],
  },
  MonkeyKing: {
    damageTypes: ["physical-damage"],
    tags: ["dash"],
    strongAgainst: ["physical-damage"],
  },
  Xayah: { damageTypes: ["physical-damage"] },
  Xerath: { damageTypes: ["magic-damage"] },
  XinZhao: { damageTypes: ["physical-damage"], tags: ["dash", "healing"] },
  Yasuo: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Yone: { damageTypes: ["physical-damage", "magic-damage"], tags: ["dash"] },
  Yorick: { damageTypes: ["physical-damage"] },
  Yuumi: { damageTypes: ["magic-damage"], tags: ["healing"] },
  Zac: { damageTypes: ["magic-damage"], tags: ["dash", "healing"] },
  Zed: { damageTypes: ["physical-damage"], tags: ["dash", "assassin"] },
  Zeri: { damageTypes: ["physical-damage"], tags: ["dash"] },
  Ziggs: { damageTypes: ["magic-damage"] },
  Zilean: { damageTypes: ["magic-damage"] },
  Zoe: { damageTypes: ["magic-damage"] },
  Zyra: { damageTypes: ["magic-damage"] },
} as const;

export type ChampionId = keyof typeof championTags;

